INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (1, N'آذربایجان شرقی', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (2, N'آذربایجان غربی', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (3, N'اردبیل', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (4, N'اصفهان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (5, N'البرز', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (6, N'ایلام', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (7, N'بوشهر', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (8, N'تهران', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (9, N'چهارمحال وبختیاری', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (10, N'خراسان جنوبی', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (11, N'خراسان رضوی', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (12, N'خراسان شمالی', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (13, N'خوزستان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (14, N'زنجان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (15, N'سمنان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (16, N'سیستان وبلوچستان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (17, N'فارس', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (18, N'قزوین', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (19, N'قم', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (20, N'کردستان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (21, N'کرمان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (22, N'کرمانشاه', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (23, N'کهگیلویه وبویراحمد', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (24, N'گلستان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (25, N'گیلان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (26, N'لرستان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (27, N'مازندران', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (28, N'مرکزی', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (29, N'هرمزگان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (30, N'همدان', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (31, N'یزد', NULL, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (32, N'آبادان', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (33, N'آباده', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (34, N'آبدانان', 6, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (35, N'آبیک', 18, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (36, N'آذرشهر', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (37, N'آرادان', 15, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (38, N'آران وبیدگل', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (39, N'آزادشهر', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (40, N'آستارا', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (41, N'آستانه اشرفیه', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (42, N'آشتیان', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (43, N'آغاجاری', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (44, N'آق قلا', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (45, N'آمل', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (46, N'آوج', 18, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (47, N'ابرکوه', 31, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (48, N'ابوموسی', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (49, N'ابهر', 14, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (50, N'اراک', 28, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (51, N'اردبیل', 3, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (52, N'اردستان', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (53, N'اردکان', 31, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (54, N'اردل', 9, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (55, N'ارزوییه', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (56, N'ارسنجان', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (57, N'ارومیه', 2, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (58, N'ازنا', 26, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (59, N'استهبان', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (60, N'اسدآباد', 30, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (61, N'اسفراین', 12, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (62, N'اسکو', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (63, N'اسلام آبادغرب', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (64, N'اسلامشهر', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (65, N'اشتهارد', 5, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (66, N'اشکذر', 31, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (67, N'اشنویه', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (68, N'اصفهان', 4, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (69, N'اصلاندوز', 3, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (70, N'اقلید', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (71, N'البرز', 18, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (72, N'الیگودرز', 26, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (73, N'املش', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (74, N'امیدیه', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (75, N'انار', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (76, N'اندیکا', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (77, N'اندیمشک', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (78, N'اوز', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (79, N'اهر', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (80, N'اهواز', 13, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (81, N'ایجرود', 14, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (82, N'ایذه', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (83, N'ایرانشهر', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (84, N'ایلام', 6, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (85, N'ایوان', 6, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (86, N'بابل', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (87, N'بابلسر', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (88, N'باخرز', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (89, N'باشت', 23, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (90, N'باغ ملک', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (91, N'بافت', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (92, N'بافق', 31, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (93, N'بانه', 20, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (94, N'باوی', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (95, N'بجستان', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (96, N'بجنورد', 12, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (97, N'بختگان', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (98, N'بدره', 6, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (99, N'برخوار', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (100, N'بردسکن', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (101, N'بردسیر', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (102, N'بروجرد', 26, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (103, N'بروجن', 9, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (104, N'بستان آباد', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (105, N'بستک', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (106, N'بشاگرد', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (107, N'بشرویه', 10, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (108, N'بم', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (109, N'بمپور', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (110, N'بن', 9, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (111, N'بناب', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (112, N'بندرانزلی', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (113, N'بندرعباس', 29, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (114, N'بندرگز', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (115, N'بندرلنگه', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (116, N'بندرماهشهر', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (117, N'بو یین و میاندشت', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (118, N'بوانات', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (119, N'بوشهر', 7, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (120, N'بوکان', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (121, N'بویراحمد', 23, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (122, N'بویین زهرا', 18, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (123, N'بهاباد', 31, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (124, N'بهار', 30, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (125, N'بهارستان', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (126, N'بهبهان', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (127, N'بهشهر', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (128, N'بهمیی', 23, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (129, N'بیجار', 20, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (130, N'بیرجند', 10, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (131, N'بیضا', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (132, N'بیله سوار', 3, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (133, N'بینالود', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (134, N'پارس آباد', 3, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (135, N'پارسیان', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (136, N'پاسارگاد', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (137, N'پاکدشت', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (138, N'پاوه', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (139, N'پردیس', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (140, N'پلدختر', 26, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (141, N'پلدشت', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (142, N'پیرانشهر', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (143, N'پیشوا', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (144, N'تاکستان', 18, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (145, N'تایباد', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (146, N'تبریز', 1, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (147, N'تربت جام', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (148, N'تربت حیدریه', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (149, N'ترکمن', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (150, N'تفت', 31, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (151, N'تفتان', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (152, N'تفرش', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (153, N'تکاب', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (154, N'تنکابن', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (155, N'تنگستان', 7, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (156, N'تویسرکان', 30, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (157, N'تهران', 8, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (158, N'تیران وکرون', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (159, N'ثلاث باباجانی', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (160, N'جاجرم', 12, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (161, N'جاسک', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (162, N'جغتای', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (163, N'جلفا', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (164, N'جم', 7, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (165, N'جوانرود', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (166, N'جویبار', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (167, N'جوین', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (168, N'جهرم', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (169, N'جیرفت', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (170, N'چادگان', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (171, N'چاراویماق', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (172, N'چالدران', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (173, N'چالوس', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (174, N'چاه بهار', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (175, N'چایپاره', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (176, N'چرام', 23, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (177, N'چرداول', 6, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (178, N'چگنی', 26, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (179, N'چناران', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (180, N'حاجی اباد', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (181, N'حمیدیه', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (182, N'خاتم', 31, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (183, N'خاش', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (184, N'خانمیرزا', 9, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (185, N'خداآفرین', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (186, N'خدابنده', 14, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (187, N'خرامه', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (188, N'خرم آباد', 26, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (189, N'خرم بید', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (190, N'خرمدره', 14, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (191, N'خرمشهر', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (192, N'خفر', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (193, N'خلخال', 3, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (194, N'خلیل آباد', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (195, N'خمیر', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (196, N'خمین', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (197, N'خمینی شهر', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (198, N'خنج', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (199, N'خنداب', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (200, N'خواف', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (201, N'خوانسار', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (202, N'خور و بیابانک', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (203, N'خوسف', 10, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (204, N'خوشاب', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (205, N'خوی', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (206, N'داراب', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (207, N'دالاهو', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (208, N'دامغان', 15, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (209, N'داورزن', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (210, N'درگز', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (211, N'درگزین', 30, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (212, N'درمیان', 10, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (213, N'دره شهر', 6, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (214, N'دزفول', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (215, N'دشت آزادگان', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (216, N'دشتستان', 7, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (217, N'دشتی', 7, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (218, N'دشتیاری', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (219, N'دلفان', 26, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (220, N'دلگان', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (221, N'دلیجان', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (222, N'دماوند', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (223, N'دنا', 23, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (224, N'دورود', 26, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (225, N'دهاقان', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (226, N'دهگلان', 20, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (227, N'دهلران', 6, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (228, N'دیر', 7, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (229, N'دیلم', 7, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (230, N'دیواندره', 20, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (231, N'رابر', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (232, N'راز و جرگلان', 12, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (233, N'راسک', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (234, N'رامسر', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (235, N'رامشیر', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (236, N'رامهرمز', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (237, N'رامیان', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (238, N'راور', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (239, N'رباط کریم', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (240, N'رزن', 30, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (241, N'رستم', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (242, N'رشت', 25, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (243, N'رشتخوار', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (244, N'رضوانشهر', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (245, N'رفسنجان', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (246, N'روانسر', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (247, N'رودان', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (248, N'رودبار', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (249, N'رودبارجنوب', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (250, N'رودسر', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (251, N'رومشکان', 26, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (252, N'ری', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (253, N'ریگان', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (254, N'زابل', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (255, N'زاوه', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (256, N'زاهدان', 16, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (257, N'زرقان', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (258, N'زرند', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (259, N'زرندیه', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (260, N'زرین دشت', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (261, N'زنجان', 14, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (262, N'زهک', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (263, N'زیرکوه', 10, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (264, N'ساری', 27, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (265, N'سامان', 9, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (266, N'ساوجبلاغ', 5, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (267, N'ساوه', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (268, N'سبزوار', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (269, N'سپیدان', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (270, N'سراب', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (271, N'سراوان', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (272, N'سرایان', 10, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (273, N'سرباز', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (274, N'سربیشه', 10, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (275, N'سرپل ذهاب', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (276, N'سرچهان', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (277, N'سرخس', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (278, N'سرخه', 15, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (279, N'سردشت', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (280, N'سرعین', 3, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (281, N'سروآباد', 20, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (282, N'سروستان', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (283, N'سقز', 20, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (284, N'سلسله', 26, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (285, N'سلطانیه', 14, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (286, N'سلماس', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (287, N'سمنان', 15, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (288, N'سمیرم', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (289, N'سنقر', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (290, N'سنندج', 20, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (291, N'سوادکوه', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (292, N'سوادکوه شمالی', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (293, N'سیاهکل', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (294, N'سیب و سوران', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (295, N'سیرجان', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (296, N'سیروان', 6, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (297, N'سیریک', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (298, N'سیمرغ', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (299, N'شادگان', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (300, N'شازند', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (301, N'شاهرود', 15, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (302, N'شاهین دژ', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (303, N'شاهین شهرومیمه', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (304, N'شبستر', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (305, N'شفت', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (306, N'شمیرانات', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (307, N'شوش', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (308, N'شوشتر', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (309, N'شوط', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (310, N'شهربابک', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (311, N'شهرضا', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (312, N'شهرکرد', 9, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (313, N'شهریار', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (314, N'شیراز', 17, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (315, N'شیروان', 12, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (316, N'صالح آباد', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (317, N'صحنه', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (318, N'صومعه سرا', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (319, N'طارم', 14, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (320, N'طالقان', 5, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (321, N'طبس', 10, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (322, N'طوالش', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (323, N'عباس آباد', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (324, N'عجب شیر', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (325, N'عسلویه', 7, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (326, N'علی آباد کتول', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (327, N'عنبرآباد', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (328, N'فارسان', 9, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (329, N'فاروج', 12, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (330, N'فاریاب', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (331, N'فامنین', 30, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (332, N'فراشبند', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (333, N'فراهان', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (334, N'فردوس', 10, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (335, N'فردیس', 5, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (336, N'فریدن', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (337, N'فریدونشهر', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (338, N'فریدونکنار', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (339, N'فریمان', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (340, N'فسا', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (341, N'فلاورجان', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (342, N'فنوج', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (343, N'فومن', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (344, N'فهرج', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (345, N'فیروزآباد', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (346, N'فیروزکوه', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (347, N'فیروزه', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (348, N'قایم شهر', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (349, N'قاینات', 10, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (350, N'قدس', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (351, N'قرچک', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (352, N'قروه', 20, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (353, N'قزوین', 18, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (354, N'قشم', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (355, N'قصرشیرین', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (356, N'قصرقند', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (357, N'قلعه گنج', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (358, N'قم', 19, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (359, N'قوچان', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (360, N'قیروکارزین', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (361, N'کارون', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (362, N'کازرون', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (363, N'کاشان', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (364, N'کاشمر', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (365, N'کامیاران', 20, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (366, N'کبودرآهنگ', 30, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (367, N'کرج', 5, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (368, N'کردکوی', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (369, N'کرمان', 21, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (370, N'کرمانشاه', 22, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (371, N'کلات', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (372, N'کلاردشت', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (373, N'کلاله', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (374, N'کلیبر', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (375, N'کمیجان', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (376, N'کنارک', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (377, N'کنگان', 7, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (378, N'کنگاور', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (379, N'کوار', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (380, N'کوثر', 3, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (381, N'کوه چنار', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (382, N'کوهبنان', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (383, N'کوهدشت', 26, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (384, N'کوهرنگ', 9, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (385, N'کوهسرخ', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (386, N'کهگیلویه', 23, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (387, N'کهنوج', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (388, N'کیار', 9, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (389, N'گالیکش', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (390, N'گتوند', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (391, N'گچساران', 23, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (392, N'گراش', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (393, N'گرگان', 24, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (394, N'گرمسار', 15, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (395, N'گرمه', 12, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (396, N'گرمی', 3, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (397, N'گلپایگان', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (398, N'گلوگاه', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (399, N'گمیشان', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (400, N'گناباد', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (401, N'گناوه', 7, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (402, N'گنبدکاووس', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (403, N'گیلانغرب', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (404, N'لارستان', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (405, N'لالی', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (406, N'لامرد', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (407, N'لاهیجان', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (408, N'لردگان', 9, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (409, N'لنجان', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (410, N'لنده', 23, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (411, N'لنگرود', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (412, N'مارگون', 23, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (413, N'ماسال', 25, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (414, N'ماکو', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (415, N'مانه وسملقان', 12, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (416, N'ماهنشان', 14, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (417, N'مبارکه', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (418, N'محلات', 28, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (419, N'محمودآباد', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (420, N'مراغه', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (421, N'مراوه تپه', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (422, N'مرند', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (423, N'مرودشت', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (424, N'مریوان', 20, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (425, N'مسجدسلیمان', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (426, N'مشگین شهر', 3, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (427, N'مشهد', 11, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (428, N'ملارد', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (429, N'ملایر', 30, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (430, N'ملکان', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (431, N'ملکشاهی', 6, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (432, N'ممسنی', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (433, N'منوجان', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (434, N'مه ولات', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (435, N'مهاباد', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (436, N'مهدی شهر', 15, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (437, N'مهر', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (438, N'مهران', 6, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (439, N'مهرستان', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (440, N'مهریز', 31, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (441, N'میامی', 15, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (442, N'میاندوآب', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (443, N'میاندورود', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (444, N'میانه', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (445, N'میبد', 31, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (446, N'میرجاوه', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (447, N'میناب', 29, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (448, N'مینودشت', 24, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (449, N'نایین', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (450, N'نجف آباد', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (451, N'نرماشیر', 21, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (452, N'نطنز', 4, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (453, N'نظرآباد', 5, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (454, N'نقده', 2, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (455, N'نکا', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (456, N'نمین', 3, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (457, N'نور', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (458, N'نوشهر', 27, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (459, N'نهاوند', 30, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (460, N'نهبندان', 10, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (461, N'نی ریز', 17, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (462, N'نیر', 3, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (463, N'نیشابور', 11, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (464, N'نیک شهر', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (465, N'نیمروز', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (466, N'ورامین', 8, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (467, N'ورزقان', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (468, N'هامون', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (469, N'هرسین', 22, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (470, N'هریس', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (471, N'هشترود', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (472, N'هفتکل', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (473, N'هلیلان', 6, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (474, N'همدان', 30, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (475, N'هندیجان', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (476, N'هوراند', 1, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (477, N'هویزه', 13, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (478, N'هیرمند', 16, 0, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (479, N'یزد', 31, 1, 1, NULL, NULL, NULL); 
INSERT INTO [cities] ([id], [name], [parent_id], [is_center], [status], [created_at], [updated_at], [deleted_at]) VALUES (480, N'یاسوج', 23, 1, 1, NULL, NULL, NULL); 
